# Generated by Django 6.0.2 on 2026-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='Номер договора')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата конца')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Полная стоимость авто')),
                ('initial_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Первоначальный взнос')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ежемесячный платеж')),
                ('payment_due_day', models.PositiveSmallIntegerField(default=1, verbose_name='День оплаты (число месяца)')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('completed', 'Завершен успешно'), ('terminated', 'Расторгнут досрочно'), ('debt', 'Есть задолженность')], default='active', max_length=20, verbose_name='Статус договора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Договор лизинга',
                'verbose_name_plural': 'Договоры лизинга',
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата осмотра')),
                ('engine_summary', models.TextField(blank=True, verbose_name='Двигатель')),
                ('body_summary', models.TextField(blank=True, verbose_name='Кузов')),
                ('suspension_summary', models.TextField(blank=True, verbose_name='Подвеска')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Осмотр',
                'verbose_name_plural': 'Осмотры',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False, verbose_name='VIN-номер')),
                ('wialon_imei', models.CharField(blank=True, help_text='Введите Unique ID из свойств Wialon', max_length=50, null=True, verbose_name='Wialon EMEI (Unique ID)')),
                ('wialon_id', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='System ID')),
                ('full_name_of_contractor', models.CharField(max_length=255, verbose_name='ФИО Исполнителя')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model_name', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('license_plate', models.CharField(max_length=15, verbose_name='Гос. номер')),
                ('video', models.FileField(blank=True, null=True, upload_to='vehicle_videos/', verbose_name='Видео обзор(MP4)')),
                ('body_type', models.CharField(choices=[('sedan', 'Седан'), ('hatchback', 'Хэтчбек'), ('suv', 'Кроссовер / Внедорожник'), ('wagon', 'Универсал'), ('coupe', 'Купе'), ('minivan', 'Минивэн'), ('pickup', 'Пикап'), ('van', 'Фургон')], default='sedan', max_length=20, verbose_name='Тип кузова')),
                ('engine_type', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро'), ('GAS', 'Газ')], default='petrol', max_length=20, verbose_name='Тип двигателя')),
                ('engine_volume', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Объём (л)')),
                ('transmission', models.CharField(choices=[('manual', 'Механика'), ('automatic', 'Автомат'), ('robot', 'Робот'), ('cvt', 'Вариатор')], default='automatic', max_length=20, verbose_name='КПП')),
                ('drive_type', models.CharField(choices=[('fwd', 'Передний (FWD)'), ('rwd', 'Задний (RWD)'), ('awd', 'Полный (AWD/4WD)')], default='fwd', max_length=10, verbose_name='Привод')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('overall_status', models.CharField(choices=[('ok', 'Исправен'), ('repair', 'Требует ремонта'), ('broken', 'Неисправен')], default='ok', max_length=10, verbose_name='Общий статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('switching_state_of_transmission', models.BooleanField(default=True, verbose_name='Работа и состояние переключения МКПП или АКПП')),
                ('noise_in_engine_operation', models.BooleanField(default=False, verbose_name='Вибрация и посторонние шумы в работе двигателя')),
                ('chassis_steering_of_the_car', models.BooleanField(default=True, verbose_name='Ходовая и рулевая часть машины')),
                ('window_operation', models.BooleanField(default=True, verbose_name='Работа стеклоподъемников')),
                ('sound_signal_operation', models.BooleanField(default=True, verbose_name='Работа звукового сигнала')),
                ('windscreen_wipers_wiper_motor', models.BooleanField(default=True, verbose_name='Дворники и моторчик стеклоочистителя')),
                ('headlights_sidelights_turn_signals', models.BooleanField(default=True, verbose_name='Фары, габариты, поворотники')),
                ('operation_of_the_steering_wheel', models.BooleanField(default=True, verbose_name='Функционирование руля и мульти-руля')),
                ('stove_in_the_salon', models.BooleanField(default=True, verbose_name='Печка салона')),
                ('electric_drive_and_condition_of_seats', models.BooleanField(default=True, verbose_name='Электрический привод и состояние сидений')),
                ('jack_screw', models.BooleanField(default=True, verbose_name='Домкрат')),
                ('spare_wheel', models.BooleanField(default=True, verbose_name='Запасное колесо')),
                ('alarms_locks_keys', models.BooleanField(default=True, verbose_name='Сигнализация, замки и ключи')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='vehicle_docs/', verbose_name='Файл (PDF)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_gallery/', verbose_name='Фотография')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фотография авто',
                'verbose_name_plural': 'Галерея фотографий',
            },
        ),
    ]
