# Generated by Django 6.0.2 on 2026-02-13 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='electric_drive_and_condition_of_seats',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='jack_screw',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='operation_of_the_steering_wheel',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='spare_wheel',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassing_rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Состояние ходовой (1-5)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Состояние двигателя (1-5)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tire_tread',
            field=models.CharField(blank=True, help_text="Например: 'Летние 5мм' или '80% износа'", max_length=100, verbose_name='Протектора шин / состояние резины'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_rating',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Состояние КПП (1-5)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='stove_in_the_salon',
            field=models.BooleanField(default=True, verbose_name='Печка/Кондиционер салона'),
        ),
    ]
