# Generated by Django 6.0.2 on 2026-02-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vehicle_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='chassing_rating',
            new_name='chassis_rating',
        ),
    ]
