# Generated by Django 6.0.2 on 2026-02-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_chassing_rating_vehicle_chassis_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='computer_assessment',
            field=models.FileField(blank=True, null=True, upload_to='assessment/', verbose_name='Компьютерная диагностика (PDF)'),
        ),
    ]
