# Generated by Django 6.0.2 on 2026-02-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_diagnosticreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticreport',
            name='comment',
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='ac_compressor',
            field=models.BooleanField(default=False, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='alternator',
            field=models.BooleanField(default=False, verbose_name='Генератор'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='brake_front_caliper_l',
            field=models.BooleanField(default=False, verbose_name='Суппорт передний (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='brake_front_caliper_r',
            field=models.BooleanField(default=False, verbose_name='Суппорт передний (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='brake_rear_caliper_l',
            field=models.BooleanField(default=False, verbose_name='Суппорт задний (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='brake_rear_caliper_r',
            field=models.BooleanField(default=False, verbose_name='Суппорт задний (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='drive_front_cv_inner_l',
            field=models.BooleanField(default=False, verbose_name='Внутренний гранат перед (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='drive_front_cv_inner_r',
            field=models.BooleanField(default=False, verbose_name='Внутренний гранат перед (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='drive_front_cv_outer_l',
            field=models.BooleanField(default=False, verbose_name='Наружный гранат перед (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='drive_front_cv_outer_r',
            field=models.BooleanField(default=False, verbose_name='Наружный гранат перед (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='drive_rear_cv_inner_l',
            field=models.BooleanField(default=False, verbose_name='Внутренний гранат зад (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='drive_rear_cv_inner_r',
            field=models.BooleanField(default=False, verbose_name='Внутренний гранат зад (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='drive_rear_cv_outer_l',
            field=models.BooleanField(default=False, verbose_name='Наружный гранат зад (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='drive_rear_cv_outer_r',
            field=models.BooleanField(default=False, verbose_name='Наружный гранат зад (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='steering_gur',
            field=models.BooleanField(default=False, verbose_name='ГУР (Гидроусилитель)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='steering_rack',
            field=models.BooleanField(default=False, verbose_name='Рулевая рейка'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='steering_tie_rod_l',
            field=models.BooleanField(default=False, verbose_name='Рулевая тяга (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='steering_tie_rod_r',
            field=models.BooleanField(default=False, verbose_name='Рулевая тяга (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='steering_tip_l',
            field=models.BooleanField(default=False, verbose_name='Рулевой наконечник (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='steering_tip_r',
            field=models.BooleanField(default=False, verbose_name='Рулевой наконечник (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='steering_ujoint',
            field=models.BooleanField(default=False, verbose_name='Крестовина рул. вала'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_camber_arm_l',
            field=models.BooleanField(default=False, verbose_name='Развальный рычаг перед (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_camber_arm_r',
            field=models.BooleanField(default=False, verbose_name='Развальный рычаг перед (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_stab_bushing_l',
            field=models.BooleanField(default=False, verbose_name='Втулки стабилизатора перед (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_stab_bushing_r',
            field=models.BooleanField(default=False, verbose_name='Втулки стабилизатора перед (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_stab_link_bushing_l',
            field=models.BooleanField(default=False, verbose_name='Втулки стоек стаб. перед (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_stab_link_bushing_r',
            field=models.BooleanField(default=False, verbose_name='Втулки стоек стаб. перед (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_stab_link_l',
            field=models.BooleanField(default=False, verbose_name='Стойка стаб. (Солдатик) перед (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_stab_link_r',
            field=models.BooleanField(default=False, verbose_name='Стойка стаб. (Солдатик) перед (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_stabilizer_l',
            field=models.BooleanField(default=False, verbose_name='Стабилизатор передний (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_front_stabilizer_r',
            field=models.BooleanField(default=False, verbose_name='Стабилизатор передний (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_beam_bushing_l',
            field=models.BooleanField(default=False, verbose_name='Сайлентблок балки (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_beam_bushing_r',
            field=models.BooleanField(default=False, verbose_name='Сайлентблок балки (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_camber_arm_l',
            field=models.BooleanField(default=False, verbose_name='Развальный рычаг зад (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_camber_arm_r',
            field=models.BooleanField(default=False, verbose_name='Развальный рычаг зад (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_soldatik_l',
            field=models.BooleanField(default=False, verbose_name='Солдатик задний (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_soldatik_r',
            field=models.BooleanField(default=False, verbose_name='Солдатик задний (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_stab_bushing_l',
            field=models.BooleanField(default=False, verbose_name='Втулки стабилизатора зад (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_stab_bushing_r',
            field=models.BooleanField(default=False, verbose_name='Втулки стабилизатора зад (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_stab_link_bushing_l',
            field=models.BooleanField(default=False, verbose_name='Втулка стоек стаб. зад (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_stab_link_bushing_r',
            field=models.BooleanField(default=False, verbose_name='Втулка стоек стаб. зад (R)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_stab_link_l',
            field=models.BooleanField(default=False, verbose_name='Стойки стабилизатора зад (L)'),
        ),
        migrations.AddField(
            model_name='diagnosticreport',
            name='susp_rear_stab_link_r',
            field=models.BooleanField(default=False, verbose_name='Стойки стабилизатора зад (R)'),
        ),
    ]
