# Generated by Django 6.0.2 on 2026-02-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_vehicle_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='initial_payment_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Введите процент (например 20)', max_digits=5, verbose_name='Процент первоначального взноса (%)'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='initial_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Первоначальный взнос'),
        ),
    ]
